# Generated by Django 2.1.7 on 2019-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180717_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notif',
            field=models.BooleanField(default=False),
        ),
    ]
