# Generated by Django 2.1.7 on 2019-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='stateId',
            field=models.CharField(default='', max_length=20, verbose_name='Id'),
            preserve_default=False,
        ),
    ]
