# Generated by Django 2.1.7 on 2019-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='drctn',
            field=models.CharField(default='810 Alton Rd, Miami Beach, FL 33139, EE. UU.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events', verbose_name='Imagen'),
        ),
    ]
