# Generated by Django 2.1.7 on 2019-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190327_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
