# Generated by Django 2.1.7 on 2019-04-17 04:48

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190330_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['status', '-id']},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.custom_upload_to, verbose_name='Imagen'),
        ),
    ]
